engines:
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
  duplication:
    enabled: true
    config:
      languages:
      - php
      - javascript
      - css
ratings:
  paths:
  - css/**
  - src/**
  - views/**
  - js/**
  - "**.php"
exclude_paths:
- bin/**/*
- test/**/*
- lib/**/*